version: '3.8'

services:
  app:
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - redis
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_REDIS_HOST=redis
    networks:
      - app-network

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
