spring:
  elasticsearch:
    uris: http://localhost:9200
  data:
    mongodb:
      host: localhost
      port: 27017
      database: appdb
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: INFO
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.redis: DEBUG 